[phases]
backend = { path = "./backend" }
frontend = { path = "./frontend" }

[install]
# Install npm-run-all globally in the container
cmd = "npm install -g npm-run-all"

[start]
cmd = "npm-run-all --parallel start:backend start:frontend"