[phases]
backend = { path = "./backend" }
frontend = { path = "./frontend" }

[build]
frontend = "cd frontend && npm install && npm run build"

[start]
# Only run backend, serve frontend as static files
cmd = "cd backend && python manage.py runserver 0.0.0.0:$PORT"