[phases.backend]
path = "./backend"
pkgs = ["python39", "python39Packages.pip"]

[phases.frontend]
path = "./frontend"
pkgs = ["nodejs-18_x", "npm"]  # Matches your Node 18 environment

[install]
cmd = """
cd frontend && npm install && \
cd ../backend && pip install -r requirements.txt
"""

[start]
cmd = "cd frontend && npm run start:all"