[phases]
backend = { 
  path = "./backend",
  # Explicitly specify Python environment
  pkgs = ["python39", "python39Packages.pip"] 
}
frontend = { 
  path = "./frontend",
  # Specify Node.js environment
  pkgs = ["nodejs"] 
}

[install]
# Install npm-run-all globally and Python dependencies
cmd = """
npm install -g npm-run-all && \
cd backend && pip install -r requirements.txt && \
cd ../frontend && npm install
"""

[start]
# Use absolute paths for reliability
cmd = "/usr/local/bin/npm-run-all --parallel start:backend start:frontend"