[phases.backend]
path = "./backend"
pkgs = ["python39", "python39Packages.pip"]

[phases.frontend]
path = "./frontend"
pkgs = ["nodejs"]

[install]
cmd = """
npm install -g npm-run-all && \
cd backend && pip install -r requirements.txt && \
cd ../frontend && npm install
"""

[start]
cmd = "/usr/local/bin/npm-run-all --parallel start:backend start:frontend"